### ISSUE TITLE
使用allinone方式安装，执行python run_toy_example.py 9999 9999 1报错

### ISSUE THREAD

**Issue by wzymmzs** [FederatedAI/FATE-Serving#117]
按照allinone的方式部署后，在host上单边测试没问题，在guest上执行python run_toy_example.py 9999 9999 1出现以下报错：

```
[ERROR] [2021-09-09 09:16:36,881] [30701:139879701149504] - task_executor.py[line:179]: ('Failed to call command: CommandURI(_uri=v1/cluster-manager/session/getOrCreateSession) to endpoint: 192.168.18.245:4670, caused by: ', <_Rendezvous of RPC that terminated with:
status = StatusCode.INTERNAL
details = "192.168.18.245:4670: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.webank.eggroll.core.command.CommandRouter$.dispatch(CommandRouter.scala:155)
at com.webank.eggroll.core.command.CommandService.com$webank$eggroll$core$command$CommandService$$run$body$1(CommandService.scala:47)
at com.webank.eggroll.core.command.CommandService$$anonfun$1.run(CommandService.scala:41)
at com.webank.eggroll.core.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:43)
at com.webank.eggroll.core.command.CommandService.call(CommandService.scala:41)
at com.webank.eggroll.core.command.CommandServiceGrpc$MethodHandlers.invoke(CommandServiceGrpc.java:217)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.webank.eggroll.core.error.ErSessionException: unable to start all processors for session id: '202109090913193330940_secure_add_example_0_0_guest_9999'. Please check corresponding bootstrap logs at 'logs//202109090913193330940_secure_add_example_0_0_guest_9999' to check the reasons. Details:
=================
total processors: 2,
started count: 0,
not started count: 2,
current active processors per node: Map(192.168.18.245 -> 0),
not started processors and their nodes: Map(2 -> 192.168.18.245, 1 -> 192.168.18.245)
at com.webank.eggroll.core.resourcemanager.SessionManagerService.getOrCreateSession(SessionManager.scala:185)
... 18 more
"
debug_error_string = "{"created":"@1631150196.872456472","description":"Error received from peer ipv4:192.168.18.245:4670","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"192.168.18.245:4670: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat com.webank.eggroll.core.command.CommandRouter$.dispatch(CommandRouter.scala:155)\n\tat com.webank.eggroll.core.command.CommandService.com$webank$eggroll$core$command$CommandService$$run$body$1(CommandService.scala:47)\n\tat com.webank.eggroll.core.command.CommandService$$anonfun$1.run(CommandService.scala:41)\n\tat com.webank.eggroll.core.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:43)\n\tat com.webank.eggroll.core.command.CommandService.call(CommandService.scala:41)\n\tat com.webank.eggroll.core.command.CommandServiceGrpc$MethodHandlers.invoke(CommandServiceGrpc.java:217)\n\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.webank.eggroll.core.error.ErSessionException: unable to start all processors for session id: '202109090913193330940_secure_add_example_0_0_guest_9999'. Please check corresponding bootstrap logs at 'logs//202109090913193330940_secure_add_example_0_0_guest_9999' to check the reasons. Details:\n=================\ntotal processors: 2, \nstarted count: 0, \nnot started count: 2, \ncurrent active processors per node: Map(192.168.18.245 -> 0), \nnot started processors and their nodes: Map(2 -> 192.168.18.245, 1 -> 192.168.18.245)\n\tat com.webank.eggroll.core.resourcemanager.SessionManagerService.getOrCreateSession(SessionManager.scala:185)\n\t... 18 more\n","grpc_status":13}"
>)
Traceback (most recent call last):
File "/data/projects/eggroll/python/eggroll/core/client.py", line 84, in sync_send
response = _command_stub.call(request.to_proto())
File "/data/projects/common/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 604, in __call__
return _end_unary_response_blocking(state, call, False, None)
File "/data/projects/common/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.INTERNAL
details = "192.168.18.245:4670: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.webank.eggroll.core.command.CommandRouter$.dispatch(CommandRouter.scala:155)
at com.webank.eggroll.core.command.CommandService.com$webank$eggroll$core$command$CommandService$$run$body$1(CommandService.scala:47)
at com.webank.eggroll.core.command.CommandService$$anonfun$1.run(CommandService.scala:41)
at com.webank.eggroll.core.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:43)
at com.webank.eggroll.core.command.CommandService.call(CommandService.scala:41)
at com.webank.eggroll.core.command.CommandServiceGrpc$MethodHandlers.invoke(CommandServiceGrpc.java:217)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.webank.eggroll.core.error.ErSessionException: unable to start all processors for session id: '202109090913193330940_secure_add_example_0_0_guest_9999'. Please check corresponding bootstrap logs at 'logs//202109090913193330940_secure_add_example_0_0_guest_9999' to check the reasons. Details:
=================
total processors: 2,
started count: 0,
not started count: 2,
current active processors per node: Map(192.168.18.245 -> 0),
not started processors and their nodes: Map(2 -> 192.168.18.245, 1 -> 192.168.18.245)
at com.webank.eggroll.core.resourcemanager.SessionManagerService.getOrCreateSession(SessionManager.scala:185)
... 18 more
"
debug_error_string = "{"created":"@1631150196.872456472","description":"Error received from peer ipv4:192.168.18.245:4670","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"192.168.18.245:4670: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat com.webank.eggroll.core.command.CommandRouter$.dispatch(CommandRouter.scala:155)\n\tat com.webank.eggroll.core.command.CommandService.com$webank$eggroll$core$command$CommandService$$run$body$1(CommandService.scala:47)\n\tat com.webank.eggroll.core.command.CommandService$$anonfun$1.run(CommandService.scala:41)\n\tat com.webank.eggroll.core.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:43)\n\tat com.webank.eggroll.core.command.CommandService.call(CommandService.scala:41)\n\tat com.webank.eggroll.core.command.CommandServiceGrpc$MethodHandlers.invoke(CommandServiceGrpc.java:217)\n\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.webank.eggroll.core.error.ErSessionException: unable to start all processors for session id: '202109090913193330940_secure_add_example_0_0_guest_9999'. Please check corresponding bootstrap logs at 'logs//202109090913193330940_secure_add_example_0_0_guest_9999' to check the reasons. Details:\n=================\ntotal processors: 2, \nstarted count: 0, \nnot started count: 2, \ncurrent active processors per node: Map(192.168.18.245 -> 0), \nnot started processors and their nodes: Map(2 -> 192.168.18.245, 1 -> 192.168.18.245)\n\tat com.webank.eggroll.core.resourcemanager.SessionManagerService.getOrCreateSession(SessionManager.scala:185)\n\t... 18 more\n","grpc_status":13}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/data/projects/python/fate_flow/operation/task_executor.py", line 128, in run_task
sess.init_computing(computing_session_id=computing_session_id, options=session_options)
File "/data/projects/python/fate_arch/session/_session.py", line 83, in init_computing
options=options)
File "/data/projects/python/fate_arch/computing/eggroll/_csession.py", line 39, in __init__
self._rp_session = session_init(session_id=session_id, options=options)
File "/data/projects/eggroll/python/eggroll/core/session.py", line 41, in session_init
er_session = ErSession(session_id=session_id, options=options)
File "/data/projects/eggroll/python/eggroll/core/session.py", line 199, in __init__
self.__session_meta = self._cluster_manager_client.get_or_create_session(session_meta)
File "/data/projects/eggroll/python/eggroll/core/client.py", line 189, in get_or_create_session
serdes_type=self.__serdes_type))
File "/data/projects/eggroll/python/eggroll/core/client.py", line 239, in __do_sync_request_internal
serdes_type=serdes_type)
File "/data/projects/eggroll/python/eggroll/core/client.py", line 67, in simple_sync_send
results = self.sync_send(inputs=[input], output_types=[output_type], endpoint=endpoint, command_uri=command_uri, serdes_type=serdes_type)
File "/data/projects/eggroll/python/eggroll/core/client.py", line 97, in sync_send
raise CommandCallError(command_uri, endpoint, e)
eggroll.core.client.CommandCallError: ('Failed to call command: CommandURI(_uri=v1/cluster-manager/session/getOrCreateSession) to endpoint: 192.168.18.245:4670, caused by: ', <_Rendezvous of RPC that terminated with:
status = StatusCode.INTERNAL
details = "192.168.18.245:4670: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.webank.eggroll.core.command.CommandRouter$.dispatch(CommandRouter.scala:155)
at com.webank.eggroll.core.command.CommandService.com$webank$eggroll$core$command$CommandService$$run$body$1(CommandService.scala:47)
at com.webank.eggroll.core.command.CommandService$$anonfun$1.run(CommandService.scala:41)
at com.webank.eggroll.core.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:43)
at com.webank.eggroll.core.command.CommandService.call(CommandService.scala:41)
at com.webank.eggroll.core.command.CommandServiceGrpc$MethodHandlers.invoke(CommandServiceGrpc.java:217)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.webank.eggroll.core.error.ErSessionException: unable to start all processors for session id: '202109090913193330940_secure_add_example_0_0_guest_9999'. Please check corresponding bootstrap logs at 'logs//202109090913193330940_secure_add_example_0_0_guest_9999' to check the reasons. Details:
=================
total processors: 2,
started count: 0,
not started count: 2,
current active processors per node: Map(192.168.18.245 -> 0),
not started processors and their nodes: Map(2 -> 192.168.18.245, 1 -> 192.168.18.245)
at com.webank.eggroll.core.resourcemanager.SessionManagerService.getOrCreateSession(SessionManager.scala:185)
... 18 more
"
debug_error_string = "{"created":"@1631150196.872456472","description":"Error received from peer ipv4:192.168.18.245:4670","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"192.168.18.245:4670: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat com.webank.eggroll.core.command.CommandRouter$.dispatch(CommandRouter.scala:155)\n\tat com.webank.eggroll.core.command.CommandService.com$webank$eggroll$core$command$CommandService$$run$body$1(CommandService.scala:47)\n\tat com.webank.eggroll.core.command.CommandService$$anonfun$1.run(CommandService.scala:41)\n\tat com.webank.eggroll.core.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:43)\n\tat com.webank.eggroll.core.command.CommandService.call(CommandService.scala:41)\n\tat com.webank.eggroll.core.command.CommandServiceGrpc$MethodHandlers.invoke(CommandServiceGrpc.java:217)\n\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.webank.eggroll.core.error.ErSessionException: unable to start all processors for session id: '202109090913193330940_secure_add_example_0_0_guest_9999'. Please check corresponding bootstrap logs at 'logs//202109090913193330940_secure_add_example_0_0_guest_9999' to check the reasons. Details:\n=================\ntotal processors: 2, \nstarted count: 0, \nnot started count: 2, \ncurrent active processors per node: Map(192.168.18.245 -> 0), \nnot started processors and their nodes: Map(2 -> 192.168.18.245, 1 -> 192.168.18.245)\n\tat com.webank.eggroll.core.resourcemanager.SessionManagerService.getOrCreateSession(SessionManager.scala:185)\n\t... 18 more\n","grpc_status":13}"
>)

```

这是什么原因？

**Comment by wzymmzs** [comment]
![image](https://user-images.githubusercontent.com/22701848/132615583-2ac3945d-f04e-4b8c-9366-4424ad653447.png)
后续的运行只有以上的报错

**Comment by awencai** [comment]
@wzymmzs 请问最后你解决了吗，怎么解决的
